### ISSUE TITLE
module 'homeassistant.components.conversation' has no attribute 'ConversationEntityFeature'

### ISSUE THREAD

**Issue by lizy14** [joselcaguilar/azure-openai-ha#83]
I encountered this error on Home Assistant 2024.7.2
```
Error while setting up azure_openai_conversation platform for conversation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/azure_openai_conversation/conversation.py", line 60, in async_setup_entry
    agent = OpenAIConversationEntity(config_entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/azure_openai_conversation/conversation.py", line 107, in __init__
    conversation.ConversationEntityFeature.CONTROL
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.conversation' has no attribute 'ConversationEntityFeature'. Did you mean: 'ConversationEntity'?
```

`ConversationEntityFeature` was added around July 2024: https://github.com/home-assistant/developers.home-assistant/pull/2237/files

It may be a good idea to update README of this project, which is currently saying:

> Home Assistant versions required: 2023.5+

**Comment by lizy14** [comment]
Just confirmed that it works on Home Assistant 2025.2.4
